---
# tasks file for udelarinterior.bind9_cluster

- debug: 
    var: bind9_cluster_zones
    verbosity: 1

- name:  Building masters's zones for bind9_zones
  set_fact: 

    bind9_zones: |
        {{ bind9_zones | default ([])
        + { "name": current_zone.name } 
        | combine ( { "type": "master" } ) 
        | combine ( { "slaves":  current_zone.bind9.secondaries | json_query ( '[].nameserver.name' ) } )
        | combine ( current_zone | json_query ( 'bind9.primary.clauses' ) )
        | combine( { "role_type": "dynamic" } | combine ( current_zone.zone ) 
                      if (current_zone.zone is defined and current_zone.zone | length > 0)
                      else { "role_type": "static" } ) 
        | json_query ( '[@]' )
        }}

  loop: '{{ bind9_cluster_zones | json_query( bind9_cluster_ns_server_zones_query ) }}'  # we loop over the zones we are master for
  loop_control:
    loop_var: current_zone  # the name (the DNS) of the zone of the current loop step
  vars:
    bind9_cluster_ns_server_zones_query: '[?bind9.primary.nameserver.hostname==`{{ inventory_hostname }}`]'  # to filter the zones whose primary NS we are

- name:  Building slave zones for bind9_zones
  set_fact: 
    bind9_zones: |
        {{ bind9_zones | default ([])
        + { "name": current_zone.name } 
        | combine ( { "type": "slave" } ) 
        | combine ( { "masters": [current_zone.bind9.primary.nameserver.name] } )
        | combine ( current_zone | json_query ( bind9_cluster_secundary_query + ".clauses" ) ) 
        | combine( { "role_type": "dynamic" } 
                      if ( current_zone.zone is defined and current_zone.zone | length > 0 )
                      else { "role_type": "static" } ) 
        | json_query ( '[@]' ) 
        }}

  loop: '{{ bind9_cluster_zones | json_query( bind9_cluster_ns_server_zones_query ) }}'
  loop_control:
    loop_var: current_zone
  vars:
    bind9_cluster_ns_server_zones_query: '[?contains( bind9.secondaries[].nameserver.hostname, `{{ inventory_hostname }}` )]'
    bind9_cluster_secundary_query: '[?nameserver.hostname==`{{ inventory_hostname }}`].clauses'
    bind9_cluster_role_config: '{{ current_zone | json_query ( bind9_cluster_secundary_query ) }}'

- name: The zones' structure for bind9 role
  debug: 
    var: bind9_zones
    verbosity: 1
  
- name: playbooks directory
  debug:
    msg: '{{ playbook_dir }}'
    verbosity: 2

- name: Build NS servers zone's variables 
  template:
    src: bind9_cluster4bind9_zones.yml.j2
    dest: '{{ bind9_cluster_hostvars_path }}/{{ bind9_cluster4bind9_zones_vars_file }}'
  delegate_to: localhost

...
